name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  gobuild:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Check out code
      uses: actions/checkout@v1
    - name: Build
      run: make build
